const imageKeys = {
    upload: require("../assets/images/uploadprofile.png"),   
    background: require("../assets/images/background.png"), 
    verifyEmail: require("../assets/images/verifyemail.png"), 
    backarrowlarge: require("../assets/images/backarrowlarge.png"), 
    backarrowsmall: require("../assets/images/backarrowsmall.png"),
    closewhite: require("../assets/images/closewhite.png"),
    confirmationwhite : require("../assets/images/confirmationwhite.png"),
    contactdriver: require("../assets/images/contactdriver.png"),
    destination: require("../assets/images/destination.png"),
    drivernavigation : require("../assets/images/drivernavigation.png"),
    dropdown : require("../assets/images/dropdown.png"),
    dropdownblack: require("../assets/images/dropdownblack.png"),
    findme : require("../assets/images/findme.png"),
    greenfilledcheck: require("../assets/images/greenfilledcheck.png"),
    help: require("../assets/images/help.png"),
    history: require("../assets/images/history.png"),
    leftarrow: require("../assets/images/leftarrow.png"),
    loading: require("../assets/images/loading.png"),
    location: require("../assets/images/location.png"),
    logout: require("../assets/images/logout.png"),
    maplightgrey: require("../assets/images/maplightgrey.png"),
    mapscreenshot: require("../assets/images/mapscreenshot.png"),
    menu: require("../assets/images/menu.png"),
    payment: require("../assets/images/payment.png"),
    plus: require("../assets/images/plus.png"),
    plusgreen: require("../assets/images/plusgreen.png"),
    profile: require("../assets/images/profile.png"),
    profileblack: require("../assets/images/profileblack.png"),
    profilegrey: require("../assets/images/profilegrey.png"),
    ratefilled: require("../assets/images/ratefilled.png"),
    recent: require("../assets/images/recent.png"),
    requesttaxiyellow: require("../assets/images/requesttaxiyellow.png"),
    scheduledridesgrey: require("../assets/images/scheduledridesgrey.png"),
    settings: require("../assets/images/settings.png"),
    smallprofileblack: require("../assets/images/smallprofileblack.png"),
    smallstar: require("../assets/images/smallstar.png"),
    stargoup: require("../assets/images/stargoup.png"),
    Star: require("../assets/images/Star.png"),
    starblacksmall: require("../assets/images/starblacksmall.png"),
    StarCopy5: require("../assets/images/StarCopy5.png"),
    Stargrey: require("../assets/images/Stargrey.png"),
    starsgroupblack: require("../assets/images/starsgroupblack.png"),
    stayyellow: require("../assets/images/stayyellow.png"),
    taxi: require("../assets/images/taxi.png"),
    taxiicon: require("../assets/images/taxiicon.png"),
    taxisearch: require("../assets/images/taxisearch.png"),
    visa: require("../assets/images/visa.png"),
    map: require("../assets/images/map.png"),
   yourlocation: require("../assets/images/yourlocation.png"),
   arrow: require("../assets/images/arrow.png"),
   threedots: require('../assets/images/threedots.jpeg'),

 };
 export default imageKeys;