const textKeys = {
    "taxiDriver":"TAXI DRIVER",
    "password": "Password",
    "ok": "OK",
    "or": "Or",
    "home": "Home",
    "am":"AM",
    "pm": "PM",
    "end": "End",
    "this": "This",
    "taxi": "TAXI",
    "driver":'DRIVER',
    "create": "Create",
    "submit": "Submit",
    "history": "History",
    'accept': 'Accept',
    'reject': "Reject",
    'pickup': "Pickup",
    'location': "Location",
    'continue': "Continue",
    'straight': "Straight",
    'destination': "Where do you need to go?",
    'left': "Left",
    'right': "Right",
    'turn': "Turn",
    "arrival": "arrival",
    "min": "min",
    "mi": "mi",
     "driverReminder": "Let People Know if you are accepting rides",
     "online": "Online",
     "offline": "Offline",
     "rideReview": "How was your Trip",
     "done": "DONE",
     'comment': "Write A Comment", 
     'opportunityMessage': "Higher ride activity today at",
     'driverOpportunity': 'Driver Opportunities',
     'from': "From",
     'to': "To",
     'the': "The",
     'day':"Day",
     'week': "Week",
     'month': "Month",
     "uploadPhoto": "Upload Photo", 
    "fullName": "Full Name",
    "phoneNumber": "Phone Number",
    "email": "Email",
    "login":{ 
        "login": "Log In",
        "username": "Username",
        "forgotPassword": "FORGOT PASSWORD?",
        "createAccount": "CREATE ACCOUNT"
    },
    "signup":{
        "createUsername": "Create Username",
        "confirmPassword": "Confirm Password"
    },
    "confirmAccount": {
        "verifYEmail": "Verify Your Email",
        "textcodeVerification": "Enter The 6 digit code sent to",
        "codeVerification": "Verification Code",
        "resendCode": "RESEND CODE",
        "allSetUp": " You're All Set Up!"
    },
    "menu":{
        "earnings": "Earnings",
        "earning": "Earning",
        "cashOut": "Cash Out",
        "trip": "Trip",
        "tripHistory": "Trip History",
        "stats": "Stats",
        "payment": "Payment",
        "info": "Info",
        "faq": "FAQ & Help",
        "settings": "Settings",
        "contact": "Contact US",
        "logout":" Log Out",
        "schedule":"Scheduled Pickups",
        "saved": "Saved Places"
    },
    "acceptTrip":{
        "acceptTrip": "Accept Trip?",
        "trip": "Trip Earnings: "
    },
    "weekDay":{
         "m": "M",
         "t": "Tu",
         "w": "W",
         "th": "Th",
         "f": "F",
         "s": "Sa",
         "su": "Su"
    },
    "rider":{
        "request":{
            'request': "Request Taxi",
            "schedule": "Scheduled Rides",
            "taxiOption": "View our other Taxi request options "
        },
        "options":{
            "goBack": "Go back to request a taxi now.",
            "course": "Book a taxi for a set amount of time.",
            "schedule": "Schedule a ride.",
            "subscribe": "Subscribe for a continuous pickup.",
            "setTime": "Set a pick up time and location.",
            "bookCourse": "Book a taxi from an hour to full day.",
            "monthSubscribe": "Subscribe to set pickups per month."
        },
        "fare":{
            "split":{
                'username': "Find username",
                'info': "Split fare with other Taxi users:",
                'price': "Total Trip Price:",
                'you': "You Pay",
                'addPerson': "Add a Person",
                'split': "Split fare",
            },
        },
        "driver":{
            "match": "Matching you with a driver",
            "wait": "Please Wait..."
        },
        "select":{
            "size": "Select Taxi Size",
            "pool": "Taxi-Pool",
            "cheap": "Cheaper, more stops",
            "benSkin": "Ben-Skin",
            'person': "person",
            'taxi': "Taxi",
            'regular': "Regular",
            'large': "Large",
            'estimate': "Estimated Price",
            'hurry': "Propose your price to drivers",
            'visa': "Visa ending in",
            'request': "Request Taxi",
        },
        'change': "change",
        'address': {
            'pickup': 'Pickup',
            'stop': "Add a Stop",
            'destination': "Destination",
            'me': "Me",
            'forme':'For Me',
            'who': "Select who's riding",
            'whor': "Who is the rider?",
            'change': "change",
            'remove': "remove",
            'places': "More saved places"
        },
        'details': "Trip Details",
        'arrival':"Arrival Time",
        'price': "Price",
        'split': "Split Fare",
        'contact': "Contact Driver",
        'cancel': "Cancel Taxi",
        'share': "Share driver info",
        'date': "Date",
    }
    
 };
 export default textKeys;